# Generated by Django 3.2.13 on 2022-05-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_q', models.CharField(max_length=120)),
                ('text_q', models.TextField()),
                ('text_answ', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
