# Generated by Django 3.2.13 on 2022-05-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_quiz',
            name='text_q',
            field=models.TextField(unique=True),
        ),
    ]
